[package]
name = "rustlib"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
roxido = { path="roxido" }
rand = "0.8.4"
rand_pcg = "0.3.1"